openapi: '3.0.2'
info:
  title: Diagn贸sticos Sec
  version: '1.0'
servers:
  - url: https://x.apigee.carloscabral.com.br/v1/diagnosticosec
paths:
  /resultado:
    post:
      description: "Resultados de diagn贸stico para um dado CPF"
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

components:
  schemas:
    Request: 
      type: object
      description: "Request de diagn贸stico. Espera CPF e Lab"
      properties:
        cpf:
          type: string
        lab:
          type: string
          enum:
            - delboni
            - lavosier
    Response: 
      type: object
      description: "Response de diagn贸stico"
      properties:
        Nome:
          type: string
        DataNascimento:
          type: string
        Sexo:
          type: string
        DataExame:
          type: string
        Resultado:
          type: string
        
        
