openapi: '3.0.2'
info:
  title: Risks
  version: '1.0'
servers:
  - url: https://x.apigee.carloscabral.com.br/v1/risks
paths:
  /score:
    post:
      description: "Given a username and CPF, returns the risk in percentage"
      parameters:
        - in: header
          name: x-apikey
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'

components:
  schemas:
    Request:
      type: object
      description: "Risk Request. Requires a name and a CPF."
      properties:
        input:
          type: object
          properties:
            name:
              type: string
            cpf:
             type: string
    Response: 
      type: object
      description: "Risk response. Replays input and adds risk."
      properties:
        input:
          type: object
          properties:
            name:
              type: string
            cpf:
             type: string
        risk:
          type: integer
        source:
          type: string