openapi: 3.0.2
info:
  title: Risks API
  version: '1.0'
  description: 'Given a set of user information, returns the risk score associated with it'
  contact:
    name: carloscabral
    email: carloscabral@google.com
    url: 'https://cloud.google.com/apigee/docs'
  license:
    name: MIT
    url: 'https://cloud.google.com/apigee/docs'
servers:
  - url: 'https://x.apigee.carloscabral.com.br/v1/risks'
paths:
  /score:
    get:
      description: 'Given a username and CPF, returns the risk in percentage'
      parameters:
        - in: header
          name: x-apikey
          schema:
            type: string
          required: true
          description: API Key
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
      operationId: getScore
components:
  schemas:
    Request:
      type: object
      description: Risk Request. Requires a name and a CPF.
      properties:
        input:
          type: object
          properties:
            name:
              type: string
            cpf:
              type: string
    Response:
      type: object
      description: Risk response. Replays input and adds risk.
      properties:
        input:
          type: object
          properties:
            name:
              type: string
            cpf:
              type: string
        risk:
          type: integer
        source:
          type: string
x-internal: false
